name: terraform-apply
on:
  push:
    branches: [ main ]
permissions:
  id-token: write
  contents: read
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: hashicorp/setup-terraform@v2
        with: { terraform_version: "1.5.0" }
      - name: Init
        run: terraform init -input=false
      - name: Plan
        run: terraform plan -input=false -out=tfplan
      - name: Apply
        run: terraform apply -input=false -auto-approve tfplan
