name: PR TFLint & Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan-per-module:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - module: modules/blob-backend
            plan_vars: |
              -var="resource_group_name=cst8918-final-project-group-4"
              -var="storage_account_name=abou0344tfstate"
              -var="container_name=tfstate"
              -var="location=canadacentral"
          - module: modules/network
            plan_vars: |
              -var="resource_group_name=cst8918-final-project-group-4"
              -var="vnet_cidr=10.0.0.0/14"
              -var='subnet_prefixes=["10.0.0.0/16","10.1.0.0/16","10.2.0.0/16","10.3.0.0/16"]'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1

      - name: Init & TFLint
        working-directory: ${{ matrix.module }}
        run: |
          terraform init -backend=false
          tflint

      - name: Plan with dummy vars
        working-directory: ${{ matrix.module }}
        run: |
          terraform init -backend=false -reconfigure
          terraform plan -out=tfplan -lock=false -input=false ${{ matrix.plan_vars }}
