name: PR TFLint & Plan

on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan-per-module:
    name: plan-${{ matrix.moduleName }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - modulePath: "modules/blob-backend"
            moduleName: "blob-backend"
            plan_vars: >-
              -var="resource_group_name=cst8918-final-project-group-4"
              -var="location=canadacentral"
              -var="storage_account_name=abou0344tfstate2"
              -var="container_name=tfstate"

          - modulePath: "modules/network"
            moduleName: "network"
            plan_vars: >-
              -var="resource_group_name=cst8918-final-project-group-4"
              -var="location=canadacentral"
              -var="vnet_cidr=10.0.0.0/14"
              -var='subnet_prefixes={prod="10.0.0.0/16",test="10.1.0.0/16",dev="10.2.0.0/16",admin="10.3.0.0/16"}'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Login is optional here (we
