name: PR TFLint & Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan-per-module:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - modules/blob-backend
          - modules/network

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1

      - name: Init, TFLint & Plan
        working-directory: ${{ matrix.module }}
        run: |
          # 1) init modules only, no backend
          terraform init -backend=false
          # 2) lint your HCL
          tflint
          # 3) full init & plan with dummy vars, no input
          terraform init -backend=false -reconfigure
          terraform plan \
            -out=tfplan \
            -lock=false \
            -input=false \
            -var="location=canadacentral" \
            -var="container_name=tfstate"
