name: PR TFLint & Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan-per-module:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Just list your module names here
        modulePath:
          - modules/blob-backend
          - modules/network

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1

      - name: Terraform Init (for lint + plan)
        run: terraform init -backend=false

      - name: TFLint
        run: tflint

      - name: Plan module ${{ matrix.modulePath }}
        run: |
          # We stay in the root, so the root provider block is in scope
          terraform plan \
            -target=module.${{ basename(matrix.modulePath) }} \
            -out=tfplan-${{ basename(matrix.modulePath) }} \
            -lock=false \
            -input=false
