name: PR TFLint & Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan-per-module:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - modulePath: "modules/blob-backend"
            moduleName: "blob-backend"
          - modulePath: "modules/network"
            moduleName: "network"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Init for lint
        run: terraform init -backend=false

      - name: TFLint
        run: tflint

      - name: Plan module ${{ matrix.moduleName }}
        working-directory: ${{ matrix.modulePath }}
        run: |
          terraform init -backend=false
          terraform plan \
            -out=tfplan-${{ matrix.moduleName }} \
            -lock=false \
            -input=false \
            -refresh=false
