name: PR TFLint & Plan

on:
  pull_request:
    branches:
      - main

jobs:
  tflint-and-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1

      - name: Terraform Init & TFLint
        run: |
          terraform init -backend=false
          tflint

      - name: Terraform Plan (no backend)
        run: |
          terraform init -backend=false -reconfigure
          terraform plan -out=tfplan -lock=false -refresh=false
