name: PR TFLint & Plan

on:
  pull_request:
    branches:
      - main

jobs:
  tflint-and-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1

      # Single init with -backend=false and -reconfigure
      - name: Terraform Init & Plan
        run: |
          terraform init -backend=false -reconfigure
          terraform plan -out=tfplan -lock=false

      - name: TFLint
        run: tflint
